const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE LANGUAGE",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  GET_ALL_PRODUCT_SEARCH_SUCCESS: "GET_ALL_PRODUCT_SEARCH_SUCCESS",
  GET_ALL_PRODUCT_SEARCH_FAILED: "GET_ALL_PRODUCT_SEARCH_FAILED",

  FETCH_ALL_REQUIRED_INFO_SUCCESS: "FETCH_ALL_REQUIRED_INFO_SUCCESS",
  FETCH_ALL_REQUIRED_INFO_FAILED: "FETCH_ALL_REQUIRED_INFO_FAILED",

  BUY_PRODUCT: "BUY_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  TOTAL_PRODUCT: "TOTAL_PRODUCT",
  DELETE_QUANTITY: "DELETE_QUANTITY",

  SET_SIDE_BAR_ON: "SET_SIDE_BAR_ON",
  SET_SIDE_BAR_OFF: "SET_SIDE_BAR_OFF",
});

export default actionTypes;
